<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nIGZpbGVuYW1lID0gbnVsbDsKT2JqZWN0IGJ5dGVDb250ZW50ID0gbnVsbDsKYm9vbGVh
biBhcHBlbmQgPSBmYWxzZTsKCklEYXRhQ3Vyc29yIGlkYyA9IHBpcGVsaW5lLmdldEN1cnNvcigp
OwoKaWRjLmZpcnN0KCJmaWxlbmFtZSIpOwpmaWxlbmFtZSA9IChTdHJpbmcpIGlkYy5nZXRWYWx1
ZSgpOwppZGMuZmlyc3QoImJ5dGVzIik7CmJ5dGVDb250ZW50ID0gKE9iamVjdCkgaWRjLmdldFZh
bHVlKCk7CmlmICggaWRjLmZpcnN0KCJvdmVyd3JpdGUiKSApIHsKCWFwcGVuZCA9ICgoU3RyaW5n
KSBpZGMuZ2V0VmFsdWUoKSkuY29tcGFyZVRvKCJmYWxzZSIpID09IDAgPyB0cnVlIDogZmFsc2U7
Cn0gZWxzZSB7CglhcHBlbmQgPSBmYWxzZTsKfQoKaW50IHRyaWVzPTA7IAp3aGlsZSh0cnVlKSB7
Cgl0cnkgewoJCUZpbGVPdXRwdXRTdHJlYW0gZj1uZXcgRmlsZU91dHB1dFN0cmVhbSgoU3RyaW5n
KShmaWxlbmFtZSksYXBwZW5kKTsgCgkJZi53cml0ZSgoYnl0ZVtdKShieXRlQ29udGVudCkpOwoJ
CWYuY2xvc2UoKTsKCQlicmVhazsKCX0gY2F0Y2goRXhjZXB0aW9uIGUpIHsKCQl0cmllcysrOwog
ICAgICAgIGlmICh0cmllcz09MjApIHsKCQkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5n
ZXRNZXNzYWdlKCkpOwoJCX0KCX0KfQppZGMuZGVzdHJveSgpOw==</value>
</Values>
